### Store processed data in a new CSV file without using built-in DataFrame export functions, manually formatting and writing the data while ensuring optimal storage efficiency.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("heart_disease.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape: (25, 14)

Columns:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

Data Types:
age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

Missing Values:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [3]:
processed_df = df.copy()

processed_df = processed_df.drop_duplicates()

processed_df = processed_df.fillna(processed_df.median(numeric_only=True))

print("Original Shape:", df.shape)
print("Processed Shape:", processed_df.shape)

Original Shape: (25, 14)
Processed Shape: (25, 14)

In [4]:
output_file = "processed_heart_disease.csv"

with open(output_file, "w", encoding="utf-8", newline="") as file:

    headers = processed_df.columns.tolist()
    file.write(",".join(headers) + "\n")

    for row in processed_df.itertuples(index=False, name=None):
        values = []

        for value in row:
            if pd.isna(value):
                values.append("")
            else:
                values.append(str(value))

        file.write(",".join(values) + "\n")

print("File created:", output_file)

File created: processed_heart_disease.csv

In [5]:
new_df = pd.read_csv("processed_heart_disease.csv")

print("New File Shape:", new_df.shape)
new_df.head()

New File Shape: (25, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1